version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: .docker/api.Dockerfile
    ports:
      - "7007:8000"
    depends_on:
      - rabbitmq
      - worker 
      - redis

  worker:
    build:
      context: .
      dockerfile: .docker/Dockerfile.worker 
    depends_on:
      - rabbitmq
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"    # RabbitMQ server port

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
