FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml poetry.lock /app/

RUN pip install --no-cache-dir poetry

RUN poetry install

COPY . /app 

CMD [ "poetry", "run", "celery", "-A", "src.worker.predict_worker", "worker", "--loglevel=info"]
